<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
/** @var Mage_Checkout_Block_Onepage_Billing $this */
?>

<form class="form--stack" id="co-billing-form" action="">
    <?php if ($this->customerHasAddresses()): ?>
        <ul class="form-list">
            <li>
                <label for="billing-address-select"><?php echo $this->__('Select from your address book or create a new address'); ?></label>

                <div class="input-box">
                    <div class="gravdept-select">
                        <?php echo $this->getAddressesHtmlSelect('billing'); ?>
                    </div>
                </div>
            </li>
        </ul>
    <?php endif; ?>

    <ul class="form-list">
        <li id="billing-new-address-form" class="fields" <?php if ($this->customerHasAddresses()): ?>style="display:none;"<?php endif; ?>>
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId(); ?>" id="billing:address_id">

            <ul>
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml(); ?>
                </li>

                <li>
                    <label for="billing:company"><?php echo $this->__('Company'); ?></label>

                    <div class="input-box">
                        <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company'); ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                    </div>
                </li>

                <?php if (!$this->isCustomerLoggedIn()): ?>
                    <li>
                        <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address'); ?></label>

                        <div class="input-box">
                            <input type="email" id="billing:email" name="billing[email]" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()); ?>" class="input-text validate-email required-entry" autocorrect="off" autocapitalize="none" spellcheck="false">
                        </div>
                    </li>
                <?php endif; ?>

                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li>
                    <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Street 1'); ?></label>

                    <div class="input-box">
                        <input type="text" id="billing:street1" name="billing[street][]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)); ?>" class="input-text <?php echo $_streetValidationClass ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                    </div>
                </li>

                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li>
                        <label for="billing:street<?php echo $_i ?>"><?php echo $this->__('Street %s', $_i); ?></label>

                        <div class="input-box">
                            <input type="text" id="billing:street<?php echo $_i ?>" name="billing[street][]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)); ?>" class="input-text <?php echo $_streetValidationClass ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                        </div>
                    </li>
                <?php endfor; ?>

                <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <li>
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>

                        <div class="input-box">
                            <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id'); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                        </div>
                    </li>
                <?php endif; ?>

                <li>
                    <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City'); ?></label>

                    <div class="input-box">
                        <input type="text" id="billing:city" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city'); ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                    </div>
                </li>

                <li>
                    <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province'); ?></label>

                    <div class="input-box">
                        <div class="gravdept-select">
                            <select id="billing:region_id" name="billing[region_id]" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province'); ?></option>
                            </select>
                        </div>

                        <script>
                            $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId(); ?>");
                        </script>

                        <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region'); ?>" style="display:none;" autocorrect="off" autocapitalize="words" spellcheck="false">
                    </div>
                </li>

                <li>
                    <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code'); ?></label>

                    <div class="input-box">
                        <input type="text" id="billing:postcode" name="billing[postcode]" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()); ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode'); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </li>

                <li>
                    <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country'); ?></label>

                    <div class="input-box">
                        <div class="gravdept-select">
                            <?php echo $this->getCountryHtmlSelect('billing'); ?>
                        </div>
                    </div>
                </li>

                <li>
                    <label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Telephone'); ?></label>

                    <div class="input-box">
                        <input type="text" id="billing:telephone" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone'); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </li>

                <li>
                    <label for="billing:fax"><?php echo $this->__('Fax'); ?></label>

                    <div class="input-box">
                        <input type="text" id="billing:fax" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax'); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </li>

                <?php if (!$this->isCustomerLoggedIn()): ?>
                    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob'); ?>
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender'); ?>

                    <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                        <?php if ($_dob->isEnabled()): ?>
                            <li>
                                <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml(); ?>
                            </li>
                        <?php endif; ?>

                        <?php if ($_gender->isEnabled()): ?>
                            <li>
                                <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml(); ?>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php if ($this->isTaxvatEnabled()): ?>
                        <li><?php echo $this->getTaxvatHtml(); ?></li>
                    <?php endif; ?>

                    <li class="fields" id="register-customer-password">
                        <div class="field">
                            <label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password'); ?></label>

                            <div class="input-box">
                                <input type="password" id="billing:customer_password" name="billing[customer_password]" class="input-text required-entry validate-password" autocorrect="off" autocapitalize="none" spellcheck="false">
                            </div>
                        </div>

                        <div class="field">
                            <label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password'); ?></label>

                            <div class="input-box">
                                <input type="password" id="billing:confirm_password" name="billing[confirm_password]" class="input-text required-entry validate-cpassword" autocorrect="off" autocapitalize="none" spellcheck="false">
                            </div>
                        </div>
                    </li>

                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                <?php endif; ?>

                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                    <li class="control">
                        <input type="checkbox" id="billing:save_in_address_book" name="billing[save_in_address_book]" value="1" onchange="if (window.shipping) shipping.setSameAsBilling(false);" <?php if ($this->getAddress()->getSaveInAddressBook()): ?>checked<?php endif;?>>
                        <label for="billing:save_in_address_book"><?php echo $this->__('Save in address book'); ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display">
                        <input type="hidden" name="billing[save_in_address_book]" value="1">
                    </li>
                <?php endif; ?>

                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>

            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </li>

        <?php if ($this->canShip()): ?>
            <li class="controls">
                <div class="control">
                    <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" <?php if ($this->isUseBillingAddressForShipping()): ?>checked<?php endif; ?> onclick="$('shipping:same_as_billing').checked = true;">
                    <label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address'); ?></label>
                </div>

                <div class="control">
                    <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0" <?php if (!$this->isUseBillingAddressForShipping()): ?>checked<?php endif; ?> onclick="$('shipping:same_as_billing').checked = false;">
                    <label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address'); ?></label>
                </div>
            </li>
        <?php endif; ?>
    </ul>

    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1">
    <?php endif; ?>

    <div class="form-buttons" id="billing-buttons-container">
        <button type="button" class="button button--cta" onclick="billing.save()"><?php echo $this->__('Continue'); ?></button>
        <span class="please-wait" id="billing-please-wait" style="display:none;"><?php echo $this->__('Loading'); ?></span>
    </div>
</form>

<script>
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress'); ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling'); ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion'); ?>', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Select State/Province...')); ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson(); ?>, undefined, 'billing:postcode');

    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');

            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }
</script>
