<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// GravDept:
// Disable "multi address checkout" link.
?>
<?php /*
<a href="<?php echo $this->getCheckoutUrl(); ?>">
    <?php echo Mage::helper('checkout')->__('Checkout with Multiple Addresses'); ?>
</a>
*/ ?>
