<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
$baseUrl = $this->getBaseUrl();
$skinUrl = $this->getSkinUrl();
?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('always_on_vacay')->toHtml() ?>
