<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist */
?>

<?php if ($this->helper('wishlist')->isAllow()): ?>
    <div class="page-title">
        <h1><?php echo $this->__('Wishlist'); ?></h1>
    </div>

    <?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
        <a class="link-rss" href="<?php echo $this->helper('wishlist')->getRssUrl($this->getWishlistInstance()->getId()); ?>">
            <?php echo $this->__('RSS Feed'); ?>
        </a>
    <?php endif; ?>

    <?php echo $this->getMessagesBlock()->toHtml(); ?>

    <?php if ($this->hasWishlistItems()): ?>
        <?php
        // GravDept:
        // ID is required by JS. Do not change.
        ?>
        <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())); ?>" method="post">
            <?php
            // GravDept:
            // Nothing for CE. Used for Magento EE.
            echo $this->getChildHtml('top');
            ?>

            <div class="button-group">
                <?php
                // GravDept:
                // See: /wishlist/button/share.phtml
                // See: /wishlist/button/tocart.phtml
                // See: /wishlist/button/update.phtml
                echo $this->getChild('control_buttons')->toHtml();
                ?>
            </div>

            <?php
            echo $this->getBlockHtml('formkey');
            $this->getChild('items')->setItems($this->getWishlistItems());
            echo $this->getChildHtml('items');
            ?>
        </form>

        <form id="wishlist-allcart-form" action="<?php echo $this->getUrl('*/*/allcart'); ?>" method="post">
            <?php echo $this->getBlockHtml('formkey'); ?>

            <input type="hidden" id="wishlist_id" name="wishlist_id" value="<?php echo $this->getWishlistInstance()->getId(); ?>">
            <input type="hidden" id="qty" name="qty" value="">
        </form>

        <?php
        // GravDept:
        // Renders only in <wishlist_index_configure> module.
        // Otherwise nothing.
        echo $this->getChildHtml('bottom');
        ?>

        <script>
            var wishlistForm        = new Validation($('wishlist-view-form'));
            var wishlistAllCartForm = new Validation($('wishlist-allcart-form'));

            function calculateQty() {
                var itemQtys = new Array();

                $$('#wishlist-view-form .qty').each(
                    function (input, index) {
                        var idxStr = input.name;
                        var idx = idxStr.replace( /[^\d.]/g, '' );
                        itemQtys[idx] = input.value;
                    }
                );

                $$('#qty')[0].value = JSON.stringify(itemQtys);
            }

            function addAllWItemsToCart() {
                calculateQty();
                wishlistAllCartForm.form.submit();
            }
        </script>
    <?php else: ?>
        <p class="lead">
            <?php echo $this->__('Your wishlist is empty.'); ?>
        </p>
    <?php endif; ?>
<?php endif; ?>
