<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
$baseUrl = $this->getBaseUrl();
$skinUrl = $this->getSkinUrl();
?>
<div class="container container--wide">
	<ul class="poster poster--big">
	    <li class="poster_item">
	        <a href="<?php echo $baseUrl; ?>" class="poster_link">
				<img class="poster_image poster_image--small" src="<?php echo $skinUrl; ?>images/home/11-012.jpg" alt="">
				<img class="poster_image poster_image--big" src="<?php echo $skinUrl; ?>images/home/21-012.jpg" alt="">
	            <div class="poster_details">
	                <div class="poster_tagline">Always looking good</div>
	                <div class="poster_title">Always on <br>Vacay...</div>
	                <span class="button">Shop Swimwear</span>
	            </div>
	        </a>
	    </li>
	</ul>
</div>
