<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>
<div class="strap strap--text strap--color">
    <div class="container">
        <ul class="promos">
            <li>Orders $75+ Ship Free</li>
            <li><strong>Spring Sale: Take 15% Off </strong><small>Use Code CHELA</small></li>
        </ul>
    </div>
</div>
