<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>

<!DOCTYPE html>
<html lang="<?php echo $this->getLang(); ?>" class="no-js">

<head>
    <?php echo $this->getChildHtml('head'); ?>
</head>

<body class="page-print <?php echo $this->getBodyClass() ? $this->getBodyClass() : ''; ?>">
    <table class="print-header-table">
        <tr>
            <td>
                <h1>
                    <img src="<?php echo $this->getPrintLogoUrl() ? $this->getPrintLogoUrl() : $this->getSkinUrl('images/logo_print.gif'); ?>" alt="<?php echo $this->getDefaultTitle(); ?>">
                </h1>
            </td>

            <?php if ($this->getPrintLogoText()): ?>
                <td class="a-right">
                    <?php echo nl2br($this->escapeHtml($this->getPrintLogoText())); ?>
                </td>
            <?php endif; ?>
        </tr>
    </table>

    <?php echo $this->getChildHtml('content'); ?>

    <button class="hide-print" onclick="window.close();">
        <?php echo $this->__('Close Window'); ?>
    </button>

    <?php echo $this->getAbsoluteFooter(); ?>
</body>
</html>
