<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
/**
 * Template for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>

<?php echo $this->getMessagesBlock()->toHtml(); ?>

<div class="page-title">
    <h1><?php echo $this->__('Your Addresses'); ?></h1>
</div>

<p>
    <a class="button button--cta" href="<?php echo $this->getAddAddressUrl(); ?>">
        <?php echo $this->__('Add Address'); ?>
    </a>
</p>

<ol class="card-list">
    <li class="card-list_item">
        <div class="card-list_card">
            <h3><?php echo $this->__('Default Billing'); ?></h3>

            <?php if ($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
                <p><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)); ?></p>

                <div class="button-group">
                    <a class="button m-b-0 button--s" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)); ?>"><?php echo $this->__('Edit'); ?></a>
                </div>
            <?php elseif ($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
                <p><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)); ?></p>

                <div class="button-group">
                    <a class="button m-b-0 button--s" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)); ?>"><?php echo $this->__('Edit'); ?></a>
                </div>
            <?php else: ?>
                <p><?php echo $this->__('You haven’t chosen a default billing address.'); ?></p>
            <?php endif; ?>
        </div>
    </li>

    <li class="card-list_item">
        <div class="card-list_card">
            <h3><?php echo $this->__('Default Shipping'); ?></h3>

            <?php if ($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
                <p><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)); ?></p>

                <div class="button-group">
                    <a class="button m-b-0 button--s" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)); ?>"><?php echo $this->__('Edit'); ?></a>
                </div>
            <?php elseif ($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
                <p><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)); ?></p>

                <div class="button-group">
                    <a class="button m-b-0 button--s" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)); ?>"><?php echo $this->__('Edit'); ?></a>
                </div>
            <?php else: ?>
                <p><?php echo $this->__('You haven’t chosen a default shipping address.'); ?></p>
            <?php endif; ?>
        </div>
    </li>
</ol>

<?php if ($_pAddsses = $this->getAdditionalAddresses()): ?>
    <h2><?php echo $this->__('Other Addresses'); ?></h2>

    <ol class="card-list card-list--four">
        <?php foreach($_pAddsses as $_address): ?>
            <li class="card-list_item">
                <div class="card-list_card">
                    <p><?php echo $this->getAddressHtml($_address); ?></p>

                    <div class="button-group">
                        <a class="button m-b-0 button--s" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())); ?>"><?php echo $this->__('Edit'); ?></a>
                        <a class="button m-b-0 button--s button--danger" href="#" onclick="return deleteAddress('<?php echo $_address->getId(); ?>');"><?php echo $this->__('Delete'); ?></a>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
<?php endif; ?>

<script>
    function deleteAddress(addressId) {
        if (confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Are you sure you want to delete this address?')); ?>')) {
            window.location='<?php echo $this->getDeleteUrl(); ?>id/' + addressId;
        }
        return false;
    }
</script>
