<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>

<?php echo $this->getMessagesBlock()->toHtml(); ?>

<?php if ($this->getTitle()): ?>
    <div class="page-title">
        <h1><?php echo $this->getTitle(); ?></h1>
    </div>
<?php endif; ?>

<form action="<?php echo $this->getSaveUrl(); ?>" method="post" id="form-validate" class="form--scaffold edit-address-form">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey'); ?>

        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl(); ?>">
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl(); ?>">

        <h2 class="legend"><?php echo $this->__('Contact Info'); ?></h2>

        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getNameBlockHtml(); ?>
            </li>

            <li>
                <label for="company"><?php echo $this->__('Company'); ?></label>

                <div class="input-box">
                    <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company'); ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                </div>
            </li>

            <li>
                <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone'); ?></label>

                <div class="input-box">
                    <input type="text" pattern="[0-9]*" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone'); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                </div>
            </li>

            <li>
                <label for="fax"><?php echo $this->__('Fax'); ?></label>

                <div class="input-box">
                    <input type="text" pattern="[0-9]*" name="fax" id="fax" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax'); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                </div>
            </li>
        </ul>
    </div>

    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Address'); ?></h2>

        <ul class="form-list">
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li class="wide">
                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address'); ?></label>
                <div class="input-box">
                    <input type="text" id="street_1" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)); ?>" class="input-text <?php echo $_streetValidationClass ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                </div>
            </li>

            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li>
                    <label for="street_<?php echo $_i ?>"><?php echo $this->__('Street Address'); ?> <?php echo $_i ?></label>
                    <div class="input-box">
                        <input type="text" id="street_<?php echo $_i; ?>" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)); ?>" class="input-text <?php echo $_streetValidationClass ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                    </div>
                </li>
            <?php endfor; ?>

            <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                <li>
                    <label for="vat_id"><?php echo $this->__('VAT Number'); ?></label>
                    <div class="input-box">
                        <input type="text" id="vat_id" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id'); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </li>
            <?php endif; ?>

            <li>
                <label for="city" class="required"><em>*</em><?php echo $this->__('City'); ?></label>

                <div class="input-box">
                    <input type="text" id="city" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city'); ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                </div>
            </li>

            <li>
                <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province'); ?></label>

                <div class="input-box">
                    <div class="gravdept-select">
                        <select id="region_id" name="region_id" class="validate-select" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province'); ?></option>
                        </select>
                    </div>

                    <script>
                        $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId(); ?>");
                    </script>

                    <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region'); ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                </div>
            </li>

            <li>
                <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code'); ?></label>

                <div class="input-box">
                    <input type="text" id="zip" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()); ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode'); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                </div>
            </li>

            <li>
                <label for="country" class="required"><em>*</em><?php echo $this->__('Country'); ?></label>

                <div class="input-box">
                    <div class="gravdept-select">
                        <?php echo $this->getCountryHtmlSelect(); ?>
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Defaults'); ?></h2>

        <ul class="form-list">
            <li class="<?php if ($this->canSetAsDefaultBilling()) echo 'control'; ?>">
                <?php if ($this->isDefaultBilling()): ?>
                    <div><?php echo $this->__('This is your default billing address.'); ?></div>
                <?php elseif ($this->canSetAsDefaultBilling()): ?>
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1">
                    <label for="primary_billing"><?php echo $this->__('Use as my default billing address.'); ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_billing" value="1">
                    <div><?php echo $this->__('This will be your default billing address.'); ?></div>
                <?php endif; ?>
            </li>

            <li class="<?php if ($this->canSetAsDefaultShipping()) echo 'control'; ?>">
                <?php if ($this->isDefaultShipping()): ?>
                    <div><?php echo $this->__('This is your default shipping address.'); ?></div>
                <?php elseif ($this->canSetAsDefaultShipping()): ?>
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1">
                    <label for="primary_shipping"><?php echo $this->__('Use as my default shipping address.'); ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_shipping" value="1">
                    <div><?php echo $this->__('This will be your default shipping address.'); ?></div>
                <?php endif; ?>
            </li>
        </ul>
    </div>

    <div class="form-buttons button-group">
        <button type="submit" class="button button--cta" data-action="save-customer-address">
            <?php echo $this->__('Save Address'); ?>
        </button>

        <a class="button button--s" href="<?php echo $this->escapeUrl($this->getBackUrl()); ?>">
            <?php echo $this->__('Cancel'); ?>
        </a>
    </div>
</form>

<script>
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson(); ?>, undefined, 'zip');
</script>
