<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php if ($this->getWishlist()->getItemsCount() && $this->getWishlist()->isSalable()): ?>
    <button type="button" class="button button--s button--cta" onclick="addAllWItemsToCart();">
        <?php echo $this->__('Add All To Cart'); ?>
    </button>
<?php endif; ?>
