<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<div id="add-review">
    <h2><?php echo $this->__('Write A Review'); ?></h2>

    <div class="media media--align-vertical m-b-1">
        <div class="media_item">
            <div class="product-image">
                <img src="<?php echo Mage::helper('catalog/image')->init($this->getProductInfo(), 'image')->resize(75); ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->getProductInfo()->getName()); ?>">
            </div>
        </div>

        <div class="media_body">
            <div class="product-name">
                <?php echo $this->escapeHtml($this->getProductInfo()->getName()); ?>
            </div>
        </div>
    </div>

    <?php if ($this->getAllowWriteReviewFlag()): ?>
        <form class="form--scaffold" id="review-form" action="<?php echo $this->getAction(); ?>" method="post">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <?php echo $this->getChildHtml('form_fields_before'); ?>

            <ul class="form-list">
                <li>
                    <label for="summary_field" class="required"><em>*</em><?php echo $this->__('Headline'); ?></label>

                    <div class="input-box">
                        <input type="text" class="input-text required-entry" id="summary_field" name="title" value="<?php echo $this->escapeHtml($data->getTitle()); ?>" autocorrect="off" autocapitalize="sentence" spellcheck="false">
                    </div>
                </li>

                <li>
                    <label for="nickname_field" class="required"><em>*</em><?php echo $this->__('Your Name'); ?></label>

                    <div class="input-box">
                        <input type="text" class="input-text required-entry" id="nickname_field" name="nickname" value="<?php echo $this->escapeHtml($data->getNickname()); ?>" autocorrect="off" autocapitalize="words" spellcheck="false">

                        <div class="input-hint">
                            <?php echo $this->__('Will be shown publicly.'); ?>
                        </div>
                    </div>
                </li>

                <?php
                // Magento:
                // Original code using TABLE and RADIO.
                ?>
                <?php /*
                <?php if ($this->getRatings() && $this->getRatings()->getSize()): ?>
                    <li>
                        <h4><?php echo $this->__('How do you rate this product?'); ?> <em class="required">*</em></h4>
                        <span id="input-message-box"></span>

                        <table class="table" id="product-review-table">
                            <thead>
                                <tr>
                                    <th>&nbsp;</th>
                                    <th><span class="nobr"><?php echo $this->__('1 star'); ?></span></th>
                                    <th><span class="nobr"><?php echo $this->__('2 stars'); ?></span></th>
                                    <th><span class="nobr"><?php echo $this->__('3 stars'); ?></span></th>
                                    <th><span class="nobr"><?php echo $this->__('4 stars'); ?></span></th>
                                    <th><span class="nobr"><?php echo $this->__('5 stars'); ?></span></th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach ($this->getRatings() as $rating): ?>
                                    <tr>
                                        <th><?php echo $this->escapeHtml($rating->getRatingCode()); ?></th>

                                        <?php foreach ($rating->getOptions() as $option): ?>
                                            <td class="value">
                                                <input type="radio" name="ratings[<?php echo $rating->getId(); ?>]" id="<?php echo $this->escapeHtml($rating->getRatingCode()); ?>_<?php echo $option->getValue(); ?>" value="<?php echo $option->getId(); ?>">
                                            </td>
                                        <?php endforeach; ?>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>

                        <input type="hidden" name="validate_rating" class="validate-rating" value="">
                    </li>
                <?php endif; ?>
                */ ?>

                <?php
                // GravDept:
                // Rebuilt code using UL and SELECT.
                ?>
                <?php if ($this->getRatings() && $this->getRatings()->getSize()): ?>
                    <?php foreach ($this->getRatings() as $rating): ?>
                        <li>
                            <label for="ratings[<?php echo $rating->getId(); ?>]" class="required"><em>*</em><?php echo $this->escapeHtml($rating->getRatingCode()); ?></label>

                            <div class="input-box">
                                <div class="gravdept-select">
                                    <select name="ratings[<?php echo $rating->getId(); ?>]" id="ratings[<?php echo $rating->getId(); ?>]">
                                        <option value=""><?php echo $this->__('Select...'); ?></option>

                                        <?php $i = 1; ?>

                                        <?php foreach ($rating->getOptions() as $option): ?>
                                            <?php if ($i === 1): ?>
                                                <option value="<?php echo $option->getId(); ?>"><?php echo $this->__('1 – Unsatisfactory'); ?></option>
                                            <?php elseif ($i === 2): ?>
                                                <option value="<?php echo $option->getId(); ?>"><?php echo $this->__('2 – Poor'); ?></option>
                                            <?php elseif ($i === 3): ?>
                                                <option value="<?php echo $option->getId(); ?>"><?php echo $this->__('3 – Average'); ?></option>
                                            <?php elseif ($i === 4): ?>
                                                <option value="<?php echo $option->getId(); ?>"><?php echo $this->__('4 – Good'); ?></option>
                                            <?php else: ?>
                                                <option value="<?php echo $option->getId(); ?>"><?php echo $this->__('5 – Excellent'); ?></option>
                                            <?php endif; ?>

                                            <?php $i++; ?>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                            <input type="hidden" name="validate_rating" class="validate-rating" value="">
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>

                <li>
                    <label for="review_field" class="required"><em>*</em><?php echo $this->__('Your Review'); ?></label>

                    <div class="input-box">
                        <textarea class="input-text required-entry" name="detail" id="review_field" rows="5" autocorrect="off" autocapitalize="sentence" spellcheck="false"><?php echo $this->escapeHtml($data->getDetail()); ?></textarea>
                    </div>
                </li>
            </ul>

            <div class="form-buttons">
                <button type="submit" class="button">
                    <?php echo $this->__('Submit Review'); ?>
                </button>
            </div>
        </form>

        <?php
        // GravDept:
        // Commented out because rating system was converted from 'TABLE and RADIO' to 'UL and SELECT'.
        ?>
        <?php /*
        <script>
            var dataForm = new VarienForm('review-form');
            Validation.addAllThese(
            [
                   ['validate-rating', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Please select one of each of the ratings above')); ?>', function(v) {
                        var trs = $('product-review-table').select('tr');
                        var inputs;
                        var error = 1;

                        for( var j=0; j < trs.length; j++ ) {
                            var tr = trs[j];
                            if ( j > 0 ) {
                                inputs = tr.select('input');

                                for( i in inputs ) {
                                    if ( inputs[i].checked == true ) {
                                        error = 0;
                                    }
                                }

                                if ( error == 1 ) {
                                    return false;
                                } else {
                                    error = 1;
                                }
                            }
                        }
                        return true;
                    }]
            ]
            );
        </script>
        */ ?>
    <?php else: ?>
        <p>
            <?php
            echo $this->__(
                'Only registered users can write reviews. Please <a href="%s">log in</a> or <a href="%s">register</a>',
                $this->getLoginLink(),
                Mage::helper('customer')->getRegisterUrl()
            );
            ?>
        </p>
    <?php endif; ?>
</div>
