<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<div class="page-title">
    <h1><?php echo $this->__('Signed Out'); ?></h1>
</div>

<p>
    <a class="button button--cta button--l" href="<?php echo $this->helper('customer')->getLoginUrl(); ?>">
        <?php echo $this->__('Sign In'); ?>
    </a>
</p>
