<?php
/**
 * Acumen - Magento Theme
 * http://gravitydept.com/to/acumen
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  2010-2016 Gravity Department. All rights reserved.
 * @license    All rights reserved.
 * @version    2.0.0
 */
?>

<?php echo $this->getMessagesBlock()->toHtml(); ?>

<div class="page-title">
    <h1><?php echo $this->__('Your Account'); ?></h1>
</div>

<div class="dashboard">
    <?php
    // See: /customer/account/dashboard/hello.phtml
    echo $this->getChildHtml('hello');

    // Info and Password
    // See: /customer/account/dashboard/info.phtml
    echo $this->getChildHtml('info');

    // Orders
    // See: /sales/order/recent.phtml
    echo $this->getChildHtml('top');
    ?>

    <div class="dashboard_section dashboard_section--newsletter">
        <div class="heading-group">
            <h2><?php echo $this->__('Newsletter'); ?></h2>

            <a class="button button--s" href="<?php echo $this->getUrl('newsletter/manage'); ?>">
                <?php echo $this->__('Manage'); ?>
            </a>
        </div>

        <p><?php echo $this->__('Edit your newsletter subscription.'); ?></p>
    </div>

    <?php
    // Addresses
    // See: /customer/account/dashboard/address.phtml
    echo $this->getChildHtml('address');

    // Reviews
    // See: /review/customer/recent.phtml
    echo $this->getChildHtml('info1');

    // Tags
    // See: /tag/customer/recent.phtml
    echo $this->getChildHtml('info2');

    // Extensions placeholder
    echo $this->getChildHtml('customer.account.dashboard.extra');
    ?>
</div>
