<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
/**
 * @see Mage_Checkout_Block_Agreements
 */
?>

<?php if ($this->getAgreements()): ?>
    <h3><?php echo $this->__('Terms & Conditions'); ?></h3>

    <form id="checkout-agreements" action="" onsubmit="return false;">
        <ol class="checkout-agreements">
            <?php foreach ($this->getAgreements() as $_a): ?>
                <li>
                    <?php
                    // GravDept:
                    // Ignore the setting from MageAdmin.
                    ?>
                    <div class="agreement-content" <?php /*echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')*/ ?>>
                        <?php if ($_a->getIsHtml()): ?>
                            <?php echo $_a->getContent(); ?>
                        <?php else: ?>
                            <?php echo nl2br($this->escapeHtml($_a->getContent())); ?>
                        <?php endif; ?>
                    </div>

                    <div class="agree control">
                        <input type="checkbox" id="agreement-<?php echo $_a->getId(); ?>" name="agreement[<?php echo $_a->getId(); ?>]" value="1">
                        <label for="agreement-<?php echo $_a->getId(); ?>"><?php echo $_a->getIsHtml() ? $_a->getCheckboxText() : $this->escapeHtml($_a->getCheckboxText()); ?></label>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </form>
<?php endif; ?>
