<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php /* @var $this Mage_Checkout_Block_Onepage_Progress */ ?>

<div class="opc-progress" id="opc-progress">
    <h2><?php echo $this->__('Summary'); ?></h2>

    <div class="opc-progress_steps">
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
            <div id="billing-progress-opcheckout" class="opc-progress_step">
                <?php echo $this->getChildHtml('billing.progress'); ?>
            </div>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <div id="shipping-progress-opcheckout" class="opc-progress_step">
                <?php echo $this->getChildHtml('shipping.progress'); ?>
            </div>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
            <div id="shipping_method-progress-opcheckout" class="opc-progress_step">
                <?php echo $this->getChildHtml('shippingmethod.progress'); ?>
            </div>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
            <div id="payment-progress-opcheckout" class="opc-progress_step">
                <?php echo $this->getChildHtml('payment.progress'); ?>
            </div>
        <?php endif; ?>
    </div>
</div>
