<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<form id="co-shipping-form" action="">
    <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId(); ?>" id="shipping:address_id">

    <?php if ($this->customerHasAddresses()): ?>
        <div class="form--stack">
            <ul class="form-list">
                <li>
                    <label for="shipping-address-select"><?php echo $this->__('Select from your address book or create a new address'); ?></label>

                    <div class="input-box">
                        <div class="gravdept-select">
                            <?php echo $this->getAddressesHtmlSelect('shipping'); ?>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    <?php endif; ?>

    <div class="form--scaffold">
        <ul class="form-list" id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml(); ?>
            </li>

            <li>
                <label for="shipping:company"><?php echo $this->__('Company'); ?></label>

                <div class="input-box">
                    <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company'); ?>" onchange="shipping.setSameAsBilling(false);" autocorrect="off" autocapitalize="words" spellcheck="false">
                </div>
            </li>

            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li>
                <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Street'); ?> 1</label>

                <div class="input-box">
                    <input type="text" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)); ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" autocorrect="off" autocapitalize="words" spellcheck="false">
                </div>
            </li>

            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li>
                    <label for="shipping:street<?php echo $_i ?>"><?php echo $this->__('Street'); ?> <?php echo $_i ?></label>

                    <div class="input-box">
                        <input type="text" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)); ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" autocorrect="off" autocapitalize="words" spellcheck="false">
                    </div>
                </li>
            <?php endfor; ?>

            <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                <li>
                    <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>

                    <div class="input-box">
                        <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id'); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </li>
            <?php endif; ?>

            <li>
                <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City'); ?></label>

                <div class="input-box">
                    <input type="text" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city'); ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" autocorrect="off" autocapitalize="words" spellcheck="false">
                </div>
            </li>

            <li>
                <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province'); ?></label>

                <div class="input-box">
                    <div class="gravdept-select">
                        <select id="shipping:region_id" name="shipping[region_id]" class="validate-select" style="display:none;">
                            <option value=""><?php echo $this->__('Please select state, region, or province'); ?></option>
                        </select>
                    </div>

                    <script>
                        $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId(); ?>");
                    </script>

                    <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region'); ?>" style="display:none;" autocorrect="off" autocapitalize="words" spellcheck="false">
                </div>
            </li>

            <li>
                <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code'); ?></label>

                <div class="input-box">
                    <input type="text" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()); ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode'); ?>" onchange="shipping.setSameAsBilling(false);" autocorrect="off" autocapitalize="none" spellcheck="false">
                </div>
            </li>

            <li>
                <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country'); ?></label>

                <div class="input-box">
                    <div class="gravdept-select">
                        <?php echo $this->getCountryHtmlSelect('shipping'); ?>
                    </div>
                </div>
            </li>

            <li>
                <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Phone'); ?></label>

                <div class="input-box">
                    <input type="text" pattern="[0-9]*" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone'); ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" autocorrect="off" autocapitalize="none" spellcheck="false">
                </div>
            </li>

            <li>
                <label for="shipping:fax"><?php echo $this->__('Fax'); ?></label>

                <div class="input-box">
                    <input type="text" pattern="[0-9]*" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax'); ?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" autocorrect="off" autocapitalize="words" spellcheck="false">
                </div>
            </li>

            <li class="controls">
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                    <div class="control">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);" <?php if ($this->getAddress()->getSaveInAddressBook()): ?>checked<?php endif;?>>
                        <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book'); ?></label>
                    </div>
                <?php else: ?>
                    <input type="hidden" name="shipping[save_in_address_book]" value="1">
                <?php endif; ?>

                <div class="control">
                    <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1" <?php if ($this->getAddress()->getSameAsBilling()): ?>checked<?php endif; ?> onclick="shipping.setSameAsBilling(this.checked)">
                    <label for="shipping:same_as_billing"><?php echo $this->__('Nevermind, use my billing address instead'); ?></label>
                </div>
            </li>

        </ul>

        <div id="shipping-buttons-container" class="form-buttons">
            <button class="button button--cta" onclick="shipping.save()"><?php echo $this->__('Continue'); ?></button>
            <span class="please-wait" id="shipping-please-wait" style="display:none;"><?php echo $this->__('Loading'); ?></span>
        </div>
    </div>
</form>

<script>
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress'); ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping'); ?>', '<?php echo $this->getUrl('checkout/onepage/shippingMethod'); ?>');
    var shippingForm = new VarienForm('co-shipping-form');

    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion'); ?>', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Select State/Province...')); ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson(); ?>, undefined, 'shipping:postcode');
</script>
