<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<p class="lead">
    <?php echo $this->__(
        'Hi %s, nice to see you!',
        $this->escapeHtml(Mage::getSingleton('customer/session')->getCustomer()->getFirstname())
        //$this->escapeHtml($this->getCustomerName())
    );
    ?>
</p>
