<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<div class="dashboard_section dashboard_section--account">
    <div class="heading-group">
        <h2><?php echo $this->__('Info and Password'); ?></h2>

        <a class="button button--s" href="<?php echo $this->getUrl('customer/account/edit'); ?>">
            <?php echo $this->__('Edit'); ?>
        </a>
    </div>

    <table class="simple-table m-b-0">
        <tr>
            <th><?php echo $this->__('Name'); ?></th>
            <td><?php echo $this->escapeHtml($this->getCustomer()->getName()); ?></td>
        </tr>

        <tr>
            <th><?php echo $this->__('Email'); ?></th>
            <td><?php echo $this->escapeHtml($this->getCustomer()->getEmail()); ?></td>
        </tr>

        <tr>
            <th><?php echo $this->__('Password'); ?></th>
            <td><a href="<?php echo $this->getChangePasswordUrl(); ?>"><?php echo $this->__('Change Password'); ?></a></td>
        </tr>
    </table>
</div>

<?php
// GravDept:
// Disable because isn't very useful.
?>
<?php /*
<?php if ( $this->isNewsletterEnabled() ): ?>
    <div class="dashboard_section dashboard_section--newsletter">
        <div class="heading-group">
            <h2><?php echo $this->__('Newsletter'); ?></h2>

            <a class="button button--s" href="<?php echo $this->getUrl('newsletter/manage'); ?>">
                <?php echo $this->__('Edit'); ?>
            </a>
        </div>

        <?php if ($this->getIsSubscribed()): ?>
            <?php echo $this->__('You’re subscribed to our newsletter.'); ?>
        <?php else: ?>
            <?php echo $this->__('You’re not subscribed to our newsletter.'); ?>
            <?php echo $this->__('Join to receive special offers and updates via email.'); ?>
        <?php endif; ?>

        <?php
        // Magento:
        // Extensions placeholder.
        echo $this->getChildHtml('customer.account.dashboard.info.extra');
        ?>
    </div>
<?php endif; ?>
*/ ?>
