<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<div class="block popular-searches">
    <div class="block_title">
        <h2><?php echo $this->__('Popular Searches'); ?></h2>
    </div>

    <div class="block_content">
        <?php if (sizeof($this->getTerms()) > 0): ?>
            <ul class="tag-list">
                <?php foreach ($this->getTerms() as $term): ?>
                    <li>
                        <a href="<?php echo $this->getSearchUrl($term); ?>" <?php /*style="font-size:<?php echo $term->getRatio()*70+75 ?>%;"*/ ?>>
                            <?php echo $this->escapeHtml($term->getName()); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <?php echo $this->__('No search terms are available.'); ?>
        <?php endif; ?>
    </div>
</div>
