<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
global $taxIter;
$taxIter++;
?>

<?php if ($this->helper('tax')->displayFullSummary() && $this->getTotal()->getValue()!=0): ?>
    <?php $isTop = 1; ?>

    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>

        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>

        <?php foreach ($rates as $rate): ?>
            <tr class="tax-details-<?php echo $taxIter; ?> tax-details<?php if ($isTop): echo ' tax-details-first'; endif; ?>" style="display:none;">
                <td style="<?php echo $this->getTotal()->getStyle(); ?>" colspan="<?php echo $this->getColspan(); ?>">
                    <?php echo $this->escapeHtml($rate['title']); ?>

                    <?php if (!is_null($rate['percent'])): ?>
                        (<?php echo (float)$rate['percent']; ?>%)
                    <?php endif; ?>
                </td>

                <?php if ($isFirst): ?>
                    <td rowspan="<?php echo count($rates); ?>" style="<?php echo $this->getTotal()->getStyle(); ?>">
                        <?php echo $this->helper('checkout')->formatPrice($amount); ?>
                    </td>
                <?php endif; ?>
            </tr>

            <?php $isFirst = 0; ?>
            <?php $isTop = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif;?>

<tr <?php if ($this->helper('tax')->displayFullSummary() && $this->getTotal()->getValue()!=0): ?>class="tax-total" onclick="expandDetails(this, '.tax-details-<?php echo $taxIter; ?>')"<?php endif; ?>>
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle(); ?>">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <div class="tax-collapse"><?php echo $this->getTotal()->getTitle(); ?></div>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle(); ?>
        <?php endif;?>
    </td>

    <td style="<?php echo $this->getTotal()->getStyle(); ?>">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()); ?></strong>
    </td>
</tr>
