<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php $product = Mage::registry('product'); ?>

<a class="button button--s" href="<?php echo $product->getProductUrl(); ?>">
    <?php echo $this->__('View Info and Buy'); ?>
</a>
