<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
$product = $this->getProduct();
$options = Mage::helper('core')->decorateArray($this->getOptions());
?>

<?php if ($product->isSaleable()): ?>
    <?php if (count($options)): ?>
        <dl class="bundle-options">
            <?php foreach ($options as $option): ?>
                <?php if (!$option->getSelections()): ?>
                    <?php continue; ?>
                <?php endif; ?>

                <?php echo $this->getOptionHtml($option); ?>
            <?php endforeach; ?>
        </dl>
    <?php else: ?>
        <p><?php echo $this->__('No options of this product are available.'); ?></p>
    <?php endif; ?>
<?php endif; ?>
