<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php $product = $this->getProduct(); ?>

<?php if ($product->isSaleable()): ?>
    <script>
        var bundle = new Product.Bundle(<?php echo $this->getJsonConfig(); ?>);
        var taxCalcMethod = "<?php echo Mage::helper('tax')->getConfig()->getAlgorithm($product->getStore()); ?>";
        var CACL_UNIT_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_UNIT_BASE ?>";
        var CACL_ROW_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_ROW_BASE ?>";
        var CACL_TOTAL_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_TOTAL_BASE ?>";
    </script>
<?php endif; ?>

<?php
// GravDept:
// Moved to: /gravdept/catalog/product/view/availability.phtml
?>
<?php /*
<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($product->isAvailable()): ?>
        <p class="availability in-stock"><?php echo $this->helper('catalog')->__('In Stock'); ?></p>
    <?php else: ?>
        <p class="availability out-of-stock"><?php echo $this->helper('catalog')->__('Out Of Stock'); ?></p>
    <?php endif; ?>
<?php endif; ?>
*/ ?>

<div class="price-box-bundle">
    <?php echo $this->getPriceHtml($product); ?>
</div>

<?php echo $this->getChildHtml('bundle_prices'); ?>
