<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// ==============================================
// GravDept:
// Global scripts to load before </body>.
// ==============================================
?>

<script src="<?php echo $this->getSkinUrl('js/build/module-app-post.min.js'); ?>"></script>

<script defer src="<?php echo $this->getSkinUrl('js/build/module-app-post-defer.min.js'); ?>"></script>
