<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// GravDept:
// Sample XML.

/*
<reference name="before_body_end">
    <block type="core/template" name="gravdept.js.module-catalog" after="-" template="gravdept/js/catalog.phtml" />
</reference>
*/
?>

<script src="<?php echo $this->getSkinUrl('js/build/module-catalog.min.js'); ?>"></script>
