<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// GravDept:
// Used by "catalogsearch" and "tag" modules.
?>

<div class="catalog-header">
    <h1>
        <?php
        if ($this->getHeaderText() || $this->getHeaderText() === false) {
            echo $this->getHeaderText();
        } else {
            echo $this->__('Searched: %s', $this->helper('catalogsearch')->getEscapedQueryText());
        }
        ?>
    </h1>
</div>
