<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php /* @var $this Mage_Catalog_Block_Product_View_Abstract */ ?>

<?php $product = $this->getProduct(); ?>

<?php
// GravDept:
// Moved to: /gravdept/catalog/product/view/availability.phtml
?>
<?php /*
<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($product->isAvailable()): ?>
        <div class="availability in-stock"><?php echo $this->__('In Stock'); ?></div>
    <?php else: ?>
        <div class="availability out-of-stock"><?php echo $this->__('Out Of Stock'); ?></div>
    <?php endif; ?>
<?php endif; ?>
*/ ?>

<?php echo $this->getChildHtml('product_type_data_extra'); ?>

<?php echo $this->getPriceHtml($product); ?>
