<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
$product = $this->getProduct();
$wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($product);
?>

<?php if ($this->helper('wishlist')->isAllow()): ?>
    <a class="add-to-wishlist-button button button--s" href="<?php echo $wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;">
        <?php echo $this->__('Add To Wishlist'); ?>
    </a>
<?php endif; ?>
