<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// **********************************************
// GravDept:
// This template only renders on the "PDP: review list" page.
// See: /review/product/view.phtml
// **********************************************
?>

<?php if (!empty($collection) && $collection->getSize()): ?>
    <table class="rating-table">
        <?php foreach ($collection as $_rating): ?>
            <?php if($_rating->getSummary()): ?>
                <tr>
                    <th><?php echo $this->__($this->escapeHtml($_rating->getRatingCode())) ?></th>

                    <td>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ceil($_rating->getSummary()) ?>%;"></div>
                        </div>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
