<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// **********************************************
// GravDept:
// Moved to: /wishlist/item/column/info.phtml
//
// No edits are made here.
// This file is only maintained to spot diffs to merge in future releases.
// **********************************************
?>

<?php /* @var Mage_Wishlist_Model_Item $item */ ?>

<?php
$item = $this->getItem();
$product = $item->getProduct();
?>

<?php /*
<a class="product-image" href="<?php echo $this->getProductUrl($item); ?>">
    <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(100, 100); ?>" alt="<?php echo $this->escapeHtml($product->getName()); ?>">
</a>
*/ ?>
