<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
/* @var Mage_Wishlist_Model_Item $item */
?>

<?php
$item = $this->getItem();
$product = $item->getProduct();
?>

<?php
// GravDept:
// Moved from: /wishlist/item/column/cart.phtml
$options = $this->getChild('customer.wishlist.item.options')->setItem($item)->getConfiguredOptions();
?>

<div class="media product-cell">
    <div class="media_item">
        <?php
        // GravDept:
        // Moved from: /wishlist/item/column/image.phtml
        ?>
        <a class="product-image" href="<?php echo $this->getProductUrl($item); ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(100, 100); ?>" alt="<?php echo $this->escapeHtml($product->getName()); ?>">
        </a>
    </div>

    <div class="media_body">
        <a class="product-name" href="<?php echo $this->getProductUrl($item); ?>">
            <?php echo $this->escapeHtml($product->getName()); ?>
        </a>

        <?php
        // GravDept:
        // Hidden.
        ?>
        <?php /*
        <div class="description std">
            <?php echo $this->escapeHtml($this->stripTags($product->getShortDescription())); ?>
        </div>
        */ ?>

        <?php
        // GravDept:
        // Moved from: /wishlist/item/column/cart.phtml
        // Also requires "$options" variable be copied (see above).
        ?>
        <div class="text--l">
            <?php echo $this->getPriceHtml($product, empty($options)); ?>
        </div>

        <?php
        // GravDept:
        //
        // Normally, Magento renders child templates when explicitly called via:
        // $this->getChildHtml('block.name')
        //
        // Then all child templates in a block-template are rendered. Before/after parameters control sorting.
        //
        // This odd code is not the normal Magento way.
        // It renders the XML-defined children, but ignores their configuration (explicit getChildHtml(), before/after position).
        // You can move this code snippet's position around, but layout XML can't do its full job.
        ?>
        <?php if ($this->getSortedChildren()): ?>
            <div class="item-manage">
                <?php foreach ($this->getSortedChildren() as $childName): ?>
                    <?php echo $this->getChildHtml($childName, false); ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <div class="wishlist_notes">
            <label for="description[<?php echo $item->getWishlistItemId(); ?>]" class="hide">
                <?php echo $this->__('Your Notes'); ?>
            </label>

            <textarea class="input-text" name="description[<?php echo $item->getWishlistItemId(); ?>]" id="description[<?php echo $item->getWishlistItemId(); ?>]" rows="2" placeholder="<?php echo $this->escapeHtml($this->__('Add notes...')); ?>"><?php echo $this->escapeHtml($item->getDescription()); ?></textarea>

            <?php
            // GravDept:
            // Useful remainder from an older version.
            // Not deprecated, but may be in the future.
            ?>
            <div class="text--subtle text--xs">
                <?php echo $this->__('Added'); ?>
                <?php echo $this->getFormatedDate($item->getAddedAt()); ?>
            </div>
        </div>
    </div>
</div>
