<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>


<?php
// GravDept:
// Moved to: /wishlist/item/column/cart.phtml
?>
<?php /*
<a class="remove-button" href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>" onclick="return confirmRemoveWishlistItem();">
    <?php echo $this->__('Remove from wishlist'); ?>
</a>
*/ ?>
