<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php echo $this->getMessagesBlock()->toHtml(); ?>

<div class="page-title">
    <h1><?php echo $this->__('Tags'); ?></h1>
</div>

<?php if ($this->getTags()): ?>
    <ul class="tag-list">
        <?php foreach ($this->getTags() as $tag): ?>
            <li class="tag-list_item">
                <a class="tag-list_button button" href="<?php echo $this->getUrl('tag/customer/view', array('tagId' => $tag->getTagId())); ?>" <?php /* style="font-size:<?php echo $tag->getRatio()*70+75 ?>%;" */ ?>>
                    <?php echo $this->escapeHtml($tag->getName()); ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p><?php echo $this->__('You haven’t tagged any products yet.'); ?></p>
<?php endif; ?>
