<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// GravDept:
// Normally this is applied to every page.
// It is only removed for "compare products" which cannot use RWD to adapt well for small screens.
?>
<meta name="viewport" content="initial-scale=1.0, width=device-width">
