<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<ul class="payment-icon-list">
    <li class="visa">
        <?php echo $this->__('Visa'); ?>
    </li>

    <li class="mastercard">
        <?php echo $this->__('MasterCard'); ?>
    </li>

    <li class="amex">
        <?php echo $this->__('American Express'); ?>
    </li>

    <li class="discover">
        <?php echo $this->__('Discover'); ?>
    </li>

    <li class="paypal">
        <?php echo $this->__('PayPal'); ?>
    </li>
</ul>
