<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// GravDept:
// Translations for use in JS.
//
// Don't indent this because it bloats the HTML needlessly.
// This is the only time we do this because nothing else belongs in this file.
?>
<script>Translator.add({
'active': '<?php echo $this->__('active'); ?>',
'Adding...': '<?php echo $this->__('Adding...'); ?>',
'Removing...': '<?php echo $this->__('Removing...'); ?>'
});</script>
