<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php /* @see Mage_Payment_Block_Info */ ?>

<h4><?php echo $this->escapeHtml($this->getMethod()->getTitle()); ?></h4>

<?php if ($_specificInfo = $this->getSpecificInformation()): ?>
    <dl class="payment-details-list">
        <?php foreach ($_specificInfo as $_label => $_value): ?>
            <dt><?php echo $this->escapeHtml($_label); ?>:</dt>
            <dd><?php echo nl2br(implode($this->getValueAsArray($_value, true), '\n')); ?></dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>

<?php echo $this->getChildHtml(); ?>
