<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<dl class="billing-methods" id="checkout-payment-method-load">
   <?php
   // Magento:
   // Content dynamically loaded.
   // Content from the methods.phtml is loaded during the ajax call.
   ?>
</dl>
