<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $this->getOrder())): ?>
    <script>
        function giftMessageToogle (giftMessageIdentifier) {
            var link      = $('order-item-gift-message-link-' + giftMessageIdentifier);
            var container = $('order-item-gift-message-' + giftMessageIdentifier);
            var row       = $('order-item-row-' + giftMessageIdentifier);

            if (link.expanded) {
                link.expanded = false;
                link.removeClassName('expanded');

                if (container.hasClassName('last')) {
                    row.addClassName('last');
                }

                container.hide();
            } else {
                link.expanded = true;
                link.addClassName('expanded');

                if (container.hasClassName('last')) {
                    row.removeClassName('last');
                }

                container.show();
            }

            return false;
        }
    </script>
<?php endif; ?>

<?php echo $this->getChildHtml('shipment_items'); ?>
