<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php if (count($this->getStores())>1): ?>
    <div class="form-language">
        <label for="select-language">
            <?php echo $this->__('Your Language:'); ?>
        </label>

        <div class="gravdept-select gravdept-select--xxs gravdept-select--compact gravdept-select--inline">
            <select class="flags" id="select-language" onchange="window.location.href=this.value">
                <?php foreach ($this->getStores() as $_lang): ?>
                    <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? 'selected' : ''; ?>

                    <option value="<?php echo $_lang->getCurrentUrl(); ?>" style="background-image:url('<?php echo $this->getSkinUrl('images/flags/flag_'.$_lang->getCode().'.gif'); ?>');" <?php echo $_selected; ?>><?php echo $this->escapeHtml($_lang->getName()); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
<?php endif; ?>

<?php
// GravDept:
// Testing flag switcher instead of dropdown.
?>
<?php /*
<?php if (count($this->getStores())>1): ?>
    <div class="form-language switcher">
        <?php foreach ($this->getStores() as $_lang): ?>
            <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? 'active' : ''; ?>

            <a class="flag" href="<?php echo $_lang->getCurrentUrl(); ?>">
                <img class="<?php echo $_selected ?>" src="<?php echo $this->getSkinUrl("img/flag/" . $_lang->getCode() . ".png"); ?>" alt="<?php echo $this->escapeHtml($_lang->getName()); ?>"/>
            </a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
*/ ?>
