<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>

<?php if (count($this->getStores()) > 1): ?>
    <div class="form-language switcher">
        <label for="select-language">
            <?php echo $this->__('Language:'); ?>
        </label>

        <div class="gravdept-select gravdept-select--xxs gravdept-select--compact gravdept-select--inline">
            <select id="select-language" onchange="window.location.href=this.value">
                <?php foreach ($this->getStores() as $_lang): ?>
                    <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected' : ''; ?>

                    <option value="<?php echo $_lang->getCurrentUrl(); ?>"<?php echo $_selected ?>><?php echo $this->escapeHtml($_lang->getName()); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
<?php endif; ?>
