<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// GravDept: [refactor]
?>

<?php
/**
 * Store switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */
?>

<?php if (count($this->getGroups())>1): ?>
    <div class="store-switcher switcher">
        <label for="select-store">
            <?php echo $this->__('Select Store:'); ?>
        </label>

        <div class="gravdept-select gravdept-select--xxs gravdept-select--compact gravdept-select--inline">
            <select id="select-store" onchange="location.href=this.value">
                <?php /*foreach ($this->getStores() as $_store): ?>
                    <option value="<?php echo $_store->getUrl(''); ?>" <?php if ($_store->getId()==$this->getCurrentStoreId()): ?>selected<?php endif; ?>><?php echo $_store->getName(); ?></option>
                <?php endforeach;*/ ?>

                <?php foreach ($this->getGroups() as $_group): ?>
                    <?php $_selected = ($_group->getId()==$this->getCurrentGroupId()) ? 'selected' : ''; ?>
                    <option value="<?php echo $_group->getHomeUrl(); ?>" <?php echo $_selected; ?>><?php echo $this->escapeHtml($_group->getName()); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
<?php endif; ?>
