<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    1.3.8
*/
?>

<?php
// GravDept:
// Modified to place category title block above sidebar filter and product list.
// Derived functionality from: /template/catalog/category/view.phtml
// Some functionality moved to: /template/gravdept/catalog/category/title-banner.phtml
?>

<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>

<?php echo $this->getMessagesBlock()->toHtml(); ?>

<?php if ($this->isContentMode()): ?>
    <div class="catalog-static-block">
        <?php echo $this->getCmsBlockHtml(); ?>
    </div>
<?php elseif ($this->isMixedMode()): ?>
    <div class="catalog-static-block">
        <?php echo $this->getCmsBlockHtml(); ?>
    </div>

    <?php echo $this->getProductListHtml(); ?>
<?php else: ?>
    <?php echo $this->getProductListHtml(); ?>
<?php endif; ?>
