<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php echo $this->getMessagesBlock()->toHtml(); ?>

<div class="page-title">
    <h1><?php echo $this->__('Contact Us'); ?></h1>
</div>

<div class="contact-grid">
    <div class="col-1">
        <form class="form--scaffold" id="contact-form" action="<?php echo $this->getFormAction(); ?>" method="post">
            <ul class="form-list">
                <li>
                    <label for="name" class="required"><em>*</em><?php echo $this->__('Name'); ?></label>

                    <div class="input-box">
                        <input type="text" class="input-text required-entry" id="name" name="name" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()); ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                    </div>
                </li>

                <li>
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email'); ?></label>

                    <div class="input-box">
                        <input type="email" class="input-text required-entry validate-email" id="email" name="email" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </li>

                <li>
                    <label for="telephone"><?php echo $this->__('Phone'); ?></label>

                    <div class="input-box">
                        <input type="text" class="input-text" pattern="[0-9*]" id="telephone" name="telephone" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </li>

                <li>
                    <label for="comment" class="required"><em>*</em><?php echo $this->__('Message'); ?></label>

                    <div class="input-box">
                        <textarea class="input-text required-entry" id="comment" name="comment" rows="5"></textarea>
                    </div>
                </li>
            </ul>

            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;">

            <div class="form-buttons">
                <button type="submit" class="button"><?php echo $this->__('Send Message'); ?></button>
            </div>
        </form>

        <script>
            var contactForm = new VarienForm('contact-form', true);
        </script>
    </div>

    <div class="col-2">
        <h2><?php echo $this->__('Email / Phone'); ?></h2>

        <p><?php echo $this->__('If you have any questions, we’d be happy to help. Please get in touch with us.'); ?></p>

        <p>
            <?php
            // GravDept:
            // Get email.
            $email = Mage::getStoreConfig('trans_email/ident_support/email');
            ?>
            <?php if ($email !== ''): ?>
                <?php echo $this->__('Email'); ?>:
                <a href="mailto:<?php echo $email; ?>">
                    <?php echo $email; ?>
                </a>
            <?php endif; ?>

            <br>

            <?php
            // GravDept:
            // Get phone.
            $phone = Mage::getStoreConfig('general/store_information/phone');
            ?>
            <?php if ($phone !== ''): ?>
                <?php echo $this->__('Phone'); ?>:
                <?php echo $phone; ?>
            <?php endif; ?>
        </p>
    </div>
</div>
