<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php echo $this->getMessagesBlock()->toHtml(); ?>

<div class="page-title">
    <h1><?php echo $this->__('Your Info and Password'); ?></h1>
</div>

<form class="form--scaffold" id="edit-account-info-form" action="<?php echo $this->getUrl('customer/account/editPost'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey'); ?>

    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Your Info'); ?></h2>

        <ul class="form-list">
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml(); ?>

            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email'); ?></label>

                <div class="input-box">
                    <input type="email" class="input-text required-entry validate-email" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                </div>
            </li>

            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob'); ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml(); ?></li>
            <?php endif; ?>

            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat'); ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml(); ?></li>
            <?php endif; ?>

            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender'); ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml(); ?></li>
            <?php endif; ?>
        </ul>
    </div>

    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Your Password'); ?></h2>

        <ul class="form-list">
            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" <?php if ($this->getCustomer()->getChangePassword()==1): ?>checked<?php endif; ?>>
                <label for="change_password"><?php echo $this->__('Change password'); ?></label>
            </li>

            <li class="fields" id="new-password-wrapper" style="display:none;">
                <div class="field">
                    <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password'); ?></label>

                    <div class="input-box">
                        <?php
                        // Magento:
                        // This is a dummy hidden field to prevent Firefox from auto filling the password
                        // if the user has saved their password in the browser's password manager.

                        // GravDept:
                        // Disable this. It is stupid and won't be maintained.
                        ?>
                        <?php /*<input type="text" class="input-text no-display" name="dummy" id="dummy">*/ ?>

                        <input type="password" class="input-text" name="current_password" id="current_password" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </div>

                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>

                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-password" name="password" id="password" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </div>

                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>

                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="form-buttons">
        <button type="submit" class="button button--cta">
            <?php echo $this->__('Update'); ?>
        </button>
    </div>
</form>

<script>
    var dataForm = new VarienForm('edit-account-info-form', true);

    function setPasswordForm (arg) {
        if (arg) {
            //$('current_password').up(3).show(); // Magento: original
            $('new-password-wrapper').show();     // GravDept: better selector. Doesn't rely on DOM parent traversal.

            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');
        } else {
            //$('current_password').up(3).hide(); // Magento: original.
            $('new-password-wrapper').hide();     // GravDept: better selector. Doesn't rely on DOM parent traversal.

            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if ($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
</script>
