<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php echo $this->getMessagesBlock()->toHtml(); ?>

<div class="page-title">
    <h1><?php echo $this->__('Forgot Password'); ?></h1>
</div>

<div class="user-auth-grid forgot-password-grid">
    <div class="col-1">
        <p><?php echo $this->__('Please enter your email address below. We will send you a link to reset your password.'); ?></p>

        <form class="form--stack" id="forgot-password-form" action="<?php echo $this->getUrl('*/*/forgotpasswordpost'); ?>" method="post">
            <ul class="form-list">
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email'); ?></label>

                    <div class="input-box">
                        <input type="email" class="input-text required-entry validate-email" id="email_address" name="email" value="<?php echo $this->escapeHtml($this->getEmailValue()); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </li>

                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>

            <div class="form-buttons">
                <button type="submit" class="button"><?php echo $this->__('Reset Password'); ?></button>
            </div>
        </form>

        <script>
            var dataForm = new VarienForm('forgot-password-form', true);
        </script>
    </div>

    <div class="col-2 std">
        <h2><?php echo $this->__('Already registered?'); ?></h2>

        <p>
            <a class="button" href="<?php echo $this->helper('customer')->getLoginUrl(); ?>">
                <?php echo $this->__('Sign In'); ?>
            </a>
        </p>

        <h2><?php echo $this->__('Register For An Account'); ?></h2>

        <ul>
            <li><?php echo $this->__('Checkout faster'); ?></li>
            <li><?php echo $this->__('Store multiple shipping addresses'); ?></li>
            <li><?php echo $this->__('View and track orders'); ?></li>
            <li><?php echo $this->__('Save items to wishlist'); ?></li>
        </ul>

        <a class="button" href="<?php echo $this->helper('customer')->getRegisterUrl(); ?>">
            <?php echo $this->__('Register'); ?>
        </a>
    </div>
</div>
