<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php echo $this->getMessagesBlock()->toHtml(); ?>

<div class="page-title">
    <h1><?php echo $this->__('Reset Your Password'); ?></h1>
</div>

<form class="form--stack" id="reset-password-form" action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post">
    <ul class="form-list">
        <li>
            <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>

            <div class="input-box">
                <input type="password" class="input-text required-entry validate-password" name="password" id="password" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false">
            </div>
        </li>

        <li>
            <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>

            <div class="input-box">
                <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false">
            </div>
        </li>
    </ul>

    <div class="form-buttons">
        <button type="submit" class="button">
            <?php echo $this->__('Reset Password'); ?>
        </button>
    </div>
</form>

<script>
    var dataForm = new VarienForm('reset-password-form', true);
</script>
