<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php /** @var $this Mage_Checkout_Block_Cart_Shipping */ ?>

<?php
$shippingRateGroups = $this->getEstimateRates();
$estimateRequested  = ($shippingRateGroups) ? true : false;
?>

<div class="shipping-estimate block" data-toggle="<?php echo ($estimateRequested) ? 'show' : 'hide'; ?>">
    <div class="block_title" data-toggle-trigger>
        <h2><?php echo $this->__('Estimate Shipping & Tax'); ?></h2>
    </div>

    <div class="block_content" data-toggle-target>
        <form class="form--stack m-b-0" id="shipping-zip-form" action="<?php echo $this->getFormActionUrl(); ?>" method="post">
            <ul class="form-list">
                <li>
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country'); ?></label>

                    <div class="input-box">
                        <div class="gravdept-select">
                            <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()); ?>
                        </div>
                    </div>
                </li>

                <?php
                // GravDept:
                // This has been commented out since Magento 1.4.0.1.
                ?>
                <?php /*if ($this->getStateActive()):*/ ?>
                    <li>
                        <label for="region_id" class="<?php if ($this->isStateProvinceRequired()) echo 'required'; ?>">
                            <?php if ($this->isStateProvinceRequired()) { echo '<em>*</em>'; } ?>
                            <?php echo $this->__('State/Province'); ?>
                        </label>

                        <div class="input-box">
                            <div class="gravdept-select">
                                <select id="region_id" name="region_id" style="display:none;"<?php echo ($this->isStateProvinceRequired() ? ' class="validate-select"' : ''); ?>>
                                    <option value=""><?php echo $this->__('Please select region, state or province'); ?></option>
                                </select>
                            </div>

                            <script>
                                $('region_id').setAttribute('defaultValue',  "<?php echo $this->getEstimateRegionId(); ?>");
                            </script>

                            <input type="text" class="input-text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getEstimateRegion()); ?>" style="display:none;" autocorrect="off" autocapitalize="words" spellcheck="false">
                        </div>
                    </li>
                <?php /*endif;*/ ?>

                <?php if ($this->getCityActive()): ?>
                    <li>
                        <label for="city" class="<?php if ($this->isCityRequired()) echo 'required'; ?>">
                            <?php if ($this->isCityRequired()) echo '<em>*</em>'; ?>
                            <?php echo $this->__('City'); ?>
                        </label>

                        <div class="input-box">
                            <input type="text" class="input-text <?php if ($this->isCityRequired()): ?>required-entry<?php endif;?>" id="city" name="estimate_city" value="<?php echo $this->escapeHtml($this->getEstimateCity()); ?>" autocorrect="off" autocapitalize="words" spellcheck="false">
                        </div>
                    </li>
                <?php endif; ?>

                <li>
                    <label for="postcode" class="<?php if ($this->isZipCodeRequired()) echo 'required'; ?>">
                        <?php if ($this->isZipCodeRequired()) echo '<em>*</em>'; ?>
                        <?php echo $this->__('Zip/Postal Code'); ?>
                    </label>

                    <div class="input-box">
                        <input type="text" class="input-text validate-postcode <?php if ($this->isZipCodeRequired()): ?>required-entry<?php endif;?>" id="postcode" name="estimate_postcode" value="<?php echo $this->escapeHtml($this->getEstimatePostcode()); ?>" autocorrect="off" autocapitalize="none" spellcheck="false">
                    </div>
                </li>
            </ul>

            <div class="form-buttons">
                <button type="button" class="button" onclick="coShippingMethodForm.submit()">
                    <?php echo $this->__('Get Estimate'); ?>
                </button>
            </div>
        </form>

        <script>
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson(); ?>);
        </script>

        <?php if ($estimateRequested): ?>
            <form class="form--stack m-t-2 m-b-0" id="co-shipping-method-form" action="<?php echo $this->getUpdateFormActionUrl(); ?>">
                <h3><?php echo $this->__('Shipping Methods'); ?></h3>

                <dl class="shipping-methods">
                    <?php foreach ($shippingRateGroups as $code => $_rates): ?>
                        <dt>
                            <?php echo $this->escapeHtml($this->getCarrierName($code)); ?>
                        </dt>

                        <dd>
                            <ul>
                                <?php foreach ($_rates as $_rate): ?>
                                    <li<?php if ($_rate->getErrorMessage()) echo ' class="error-msg"'; ?>>
                                       <?php if ($_rate->getErrorMessage()): ?>
                                            <?php echo $_rate->getErrorMessage(); ?>
                                       <?php else: ?>
                                            <input name="estimate_method" type="radio" value="<?php echo $this->escapeHtml($_rate->getCode()); ?>" id="s_method_<?php echo $_rate->getCode(); ?>" <?php if ($_rate->getCode()===$this->getAddressShippingMethod()) echo 'checked'; ?>>

                                            <label for="s_method_<?php echo $_rate->getCode(); ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()); ?>
                                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                                                <?php echo $_excl; ?>

                                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                                <?php endif; ?>
                                            </label>
                                       <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </dd>
                    <?php endforeach; ?>
                </dl>

                <div class="form-buttons">
                    <button type="submit" class="button">
                        <?php echo $this->__('Update Order Total'); ?>
                    </button>
                </div>
            </form>
        <?php endif; ?>
    </div>
</div>

<script>
    var coShippingMethodForm = new VarienForm('shipping-zip-form');
    var countriesWithOptionalZip = <?php echo $this->helper('directory')->getCountriesWithOptionalZip(true); ?>;

    coShippingMethodForm.submit = function () {
        // GravDept: [refactor]
        // What's the "$F" for?
        var country = $F('country');
        var optionalZip = false;

        for (i=0; i < countriesWithOptionalZip.length; i++) {
            if (countriesWithOptionalZip[i] == country) {
                optionalZip = true;
            }
        }
        if (optionalZip) {
            $('postcode').removeClassName('required-entry');
        }
        else {
            $('postcode').addClassName('required-entry');
        }
        return VarienForm.prototype.submit.bind(coShippingMethodForm)();
    }
</script>
