<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
    <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none;">
        <?php if ($this->getMethod()->getPayableTo()): ?>
            <li>
                <label><?php echo $this->__('Make check payable to'); ?></label>

                <div class="input-box">
                    <?php echo $this->escapeHtml($this->getMethod()->getPayableTo()); ?>
                </div>
            </li>
        <?php endif; ?>

        <?php if ($this->getMethod()->getMailingAddress()): ?>
            <li>
                <label><?php echo Mage::helper('payment')->__('Mail check to'); ?></label>

                <div class="input-box">
                    <?php echo nl2br($this->escapeHtml($this->getMethod()->getMailingAddress())); ?>
                </div>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
