<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>

<tr>
    <td>
        <div class="media product-cell">
            <a class="product-image media_item" href="<?php echo $this->getProductUrl(); ?>">
                <img src="<?php echo $this->getProductThumbnail()->resize(100, 100); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()); ?>">
            </a>

            <div class="media_body">
                <?php if ($this->hasProductUrl()): ?>
                    <div>
                        <a class="product-name" href="<?php echo $this->getProductUrl(); ?>">
                            <?php echo $this->escapeHtml($this->getProductName()); ?>
                        </a>
                    </div>
                <?php else: ?>
                    <div class="product-name">
                        <?php echo $this->escapeHtml($this->getProductName()); ?>
                    </div>
                <?php endif; ?>

                <?php
                // GravDept:
                // Clone unit price.
                // See: /skin/.../js/src/cart.js
                ?>
                <div class="clone-price is-linearized-show-elem"></div>

                <?php if ($options = $this->getOptionList()): ?>
                    <ul class="item-options-list">
                        <?php foreach ($options as $option) : ?>
                            <li>
                                <?php $formatedOptionValue = $this->getFormatedOptionValue($option); ?>

                                <strong><?php echo $this->escapeHtml($option['label']); ?>:</strong>

                                <span <?php if (isset($formatedOptionValue['full_view'])): ?>class="truncated"<?php endif; ?>>
                                    <?php echo $formatedOptionValue['value'] ?>

                                    <?php if (isset($formatedOptionValue['full_view'])): ?>
                                        <div class="truncated_full_value">
                                            <dl class="item-options">
                                                <dt><?php echo $this->escapeHtml($option['label']); ?></dt>
                                                <dd><?php echo $formatedOptionValue['full_view'] ?></dd>
                                            </dl>
                                        </div>
                                    <?php endif; ?>
                                </span>
                            </li>
                        <?php endforeach; ?>
                    </ul>

                    <?php
                    // GravDept:
                    // Only show for products with options.
                    ?>
                    <?php if ($isVisibleProduct): ?>
                        <a class="edit-options-link" href="<?php echo $this->getConfigureUrl(); ?>">
                            <?php echo $this->__('Edit Options'); ?>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($messages = $this->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']); ?></p>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?php echo $addInfoBlock->setItem($_item)->toHtml(); ?>
                <?php endif; ?>
            </div>
        </div>
    </td>



    <?php
    // ----------------------------------------------
    // GravDept:
    // Start "unit price".
    ?>

    <?php if ($canApplyMsrp): ?>
        <?php
        // GravDept:
        // Add utility classes.
        ?>
        <td class="a-center is-linearized-hide-cell text--l" data-clone-price-origin <?php if ($this->helper('tax')->displayCartBothPrices()): ?>colspan="2"<?php endif; ?>>
            <span class="cart-price">
                <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__('What\'s this?'); ?></a>
                <script>
                    Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__('What\'s this?'); ?>");
                </script>
            </span>
        </td>
    <?php else: ?>
        <?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
            <?php
            // GravDept:
            // Add utility classes.
            ?>
            <td class="a-center is-linearized-hide-cell text--l" data-clone-price-origin>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                    <?php else: ?>
                        <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()); ?>
                    <?php endif; ?>
                </span>

                <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                    <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
        <?php endif; ?>

        <!-- inclusive price starts here -->
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <?php
            // GravDept:
            // Add utility classes.
            ?>
            <td class="a-center is-linearized-hide-cell text--l">
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
                    <?php else: ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()); ?>
                    <?php endif; ?>
                </span>

                <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                    <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee">
                                <?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:
                                <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
                            </span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
        <?php endif; ?>
    <?php endif; ?>

    <?php
    // GravDept:
    // End "unit price".
    // ----------------------------------------------
    ?>



    <td class="a-center">
        <div class="cart-row-actions">
            <div class="stepper">
                <label class="stepper_label hide" for="cart[<?php echo $_item->getId() ?>][qty]">
                    <?php echo $this->__('Quantity'); ?>
                </label>

                <div class="stepper_liner">
                    <button type="button" class="stepper_button stepper_button--down">
                        <?php echo $this->__('Decrease quantity'); ?>
                    </button>

                    <input type="text" pattern="[0-9]*" class="input-text stepper_input" name="cart[<?php echo $_item->getId() ?>][qty]" id="cart[<?php echo $_item->getId(); ?>][qty]" value="<?php echo $this->getQty(); ?>">

                    <button type="button" class="stepper_button stepper_button--up">
                        <?php echo $this->__('Increase quantity'); ?>
                    </button>
                </div>
            </div>

            <div>
                <a class="remove-link" href="<?php echo $this->getDeleteUrl(); ?>">
                    <?php echo $this->__('Remove'); ?>
                </a>
            </div>
        </div>
    </td>



    <?php
    // ----------------------------------------------
    // GravDept:
    // Start "subtotal".
    ?>

    <?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
        <?php
        // GravDept:
        // Add utility classes.
        ?>
        <td class="a-center is-linearized-hide-cell text--l">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-msrp-subtotal">--</span>
                <?php else: ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                    <?php else: ?>
                        <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()); ?>
                    <?php endif; ?>
                <?php endif; ?>
            </span>

            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
    <?php endif; ?>

    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php
        // GravDept:
        // Add utility classes.
        ?>
        <td class="a-center is-linearized-hide-cell text--l">
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-msrp-subtotal">--</span>
                <?php else: ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                    <?php else: ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()); ?>
                    <?php endif; ?>
                <?php endif; ?>

            </span>

            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee">
                            <?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:
                            <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                        </span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
    <?php endif; ?>

    <?php
    // GravDept:
    // End "subtotal".
    // ----------------------------------------------
    ?>



    <?php
    // GravDept:
    // Hide "move to wishlist".
    // This disrupts checkout flow.
    ?>
    <?php /*
    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
        <td class="a-center is-linearized-hide-cell">
            <?php if ($isVisibleProduct): ?>
            <a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="link-wishlist use-ajax"><?php echo $this->__('Move'); ?></a>
            <?php endif; ?>
        </td>
    <?php endif; ?>
    */ ?>
</tr>
