<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<!DOCTYPE html>
<html lang="<?php echo $this->getLang(); ?>" class="no-js">

<head>
    <?php echo $this->getChildHtml('head'); ?>
</head>

<body class="<?php echo $this->getBodyClass() ? $this->getBodyClass() : ''; ?>">
    <?php echo $this->getChildHtml('after_body_start'); ?>
    <?php echo $this->getChildHtml('global_notices'); ?>

    <div class="site-wrap">
        <?php echo $this->getChildHtml('header'); ?>

        <div class="site-matter">
            <div class="container">
                <?php
                // GravDept:
                // Custom block.
                echo $this->getChildHtml('gravdept_catalog_header');

                echo $this->getChildHtml('global_messages');

                // GravDept:
                // Relocated here.
                echo $this->getChildHtml('compare_sidebar');
                ?>

                <div class="offscreen-catalog">
                    <div class="offscreen-catalog_trigger">
                        <button
                        class="button button--s"
                        data-offscreen="catalog"
                        data-offscreen-show="<?php echo Mage::helper('core')->quoteEscape($this->__('Show Filters')); ?>"
                        data-offscreen-hide="<?php echo Mage::helper('core')->quoteEscape($this->__('Hide Filters')); ?>">
                            <span class="label"><?php echo $this->__('Show Filters'); ?></span>
                            <span class="count" data-filters-count="0"></span>
                        </button>
                    </div>

                    <div class="offscreen-catalog_wrapper">
                        <div class="offscreen-catalog_sidebar">
                            <?php echo $this->getChildHtml('left'); ?>

                            <?php
                            // GravDept: get snippet.
                            $snippet = $this->getLayout()->createBlock('cms/block')->setBlockId('snippet_catalog_sidebar_below')->toHtml();
                            echo ($snippet) ? $snippet : '';
                            ?>
                        </div>

                        <div class="offscreen-catalog_content">
                            <?php echo $this->getChildHtml('content'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php echo $this->getChildHtml('footer'); ?>
    </div>

    <?php echo $this->getChildHtml('global_cookie_notice'); ?>
    <?php echo $this->getChildHtml('before_body_end'); ?>
    <?php echo $this->getAbsoluteFooter(); ?>
</body>
</html>
