<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// ==============================================
// GravDept:
// This pager is used only in account dashboard.
// Not in the catalog.
// ==============================================
?>

<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>

<?php if ($this->getCollection()->getSize()): ?>
    <?php
    // GravDept: pagination.
    ?>
    <div class="toolbar_pager">
        <?php if ($this->getLastPageNum() > 1): ?>
            <ol class="pages">
                <?php if ($this->canShowPreviousJump()): ?>
                    <li>
                        <a class="previous-jump" href="<?php echo $this->getPreviousJumpUrl(); ?>">...</a>
                    </li>
                <?php endif; ?>

                <?php if (!$this->isFirstPage()): ?>
                    <li>
                        <a class="previous <?php if (!$this->getAnchorTextForPrevious()): ?>i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl(); ?>">
                            <?php if (!$this->getAnchorTextForPrevious()): ?>
                                <?php echo $this->__('Previous'); ?>
                            <?php else: ?>
                                <?php echo $this->getAnchorTextForPrevious(); ?>
                            <?php endif;?>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($this->canShowFirst()): ?>
                    <li><a class="first" href="<?php echo $this->getFirstPageUrl(); ?>">1</a></li>
                <?php endif;?>

                <?php foreach ($this->getFramePages() as $_page): ?>
                    <?php if ($this->isPageCurrent($_page)): ?>
                        <li><span class="current"><?php echo $_page ?></span></li>
                    <?php else: ?>
                        <li><a href="<?php echo $this->getPageUrl($_page); ?>"><?php echo $_page ?></a></li>
                    <?php endif;?>
                <?php endforeach;?>

                <?php if ($this->canShowLast()): ?>
                  <li><a class="last" href="<?php echo $this->getLastPageUrl(); ?>"><?php echo $this->getLastPageNum(); ?></a><li>
                <?php endif;?>

                <?php if (!$this->isLastPage()): ?>
                    <li>
                        <a class="next <?php if (!$this->getAnchorTextForNext()): ?>i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl(); ?>">
                            <?php if (!$this->getAnchorTextForNext()): ?>
                                <?php echo $this->__('Next'); ?>
                            <?php else: ?>
                                <?php echo $this->getAnchorTextForNext(); ?>
                            <?php endif;?>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($this->canShowNextJump()): ?>
                    <li>
                        <a class="next-jump" href="<?php echo $this->getNextJumpUrl(); ?>">...</a>
                    </li>
                <?php endif;?>
            </ol>
        <?php endif; ?>
    </div>

    <?php
    // GravDept: amounts.
    ?>
    <?php if ($this->getShowAmounts()): ?>
        <div class="toolbar_amount">
            <?php if ($this->getLastPageNum()>1): ?>
                <?php echo $this->__('<strong>%s–%s</strong> of %s items', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()); ?>
            <?php elseif ( $this->getLastPageNum()==1 && $this->getTotalNum()==1 ): ?>
                <?php echo $this->__('%s items', $this->getTotalNum()); ?>
            <?php else: ?>
                <?php echo $this->__('%s items', $this->getTotalNum()); ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php
    // GravDept: limit products.
    ?>
    <?php if ($this->getShowPerPage()): ?>
        <div class="toolbar_limit">
            <label for="pager-show">
                <?php echo $this->__('Show'); ?>
            </label>

            <div class="gravdept-select gravdept-select--xxs gravdept-select--compact gravdept-select--inline">
                <select id="pager-show" onchange="setLocation(this.value)">
                    <?php foreach ($this->getAvailableLimit() as $_key=>$_limit): ?>
                        <option value="<?php echo $this->getLimitUrl($_key); ?>" <?php if ($this->isLimitCurrent($_key)): ?>selected<?php endif; ?>>
                            <?php
                            echo $_limit;

                            if (is_numeric($_limit)) {
                                echo $this->__(' per page');
                            }

                            if (!is_numeric($_limit)) {
                                echo $this->__(' items');
                            }
                            ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
