<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// **********************************************
// GravDept:
// Used in catalog lists.
// **********************************************
?>

<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()): ?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary(); ?>%"></div>
            </div>
        <?php endif; ?>

        <?php
        // GravDept:
        // Hide in lists.
        ?>
        <?php /*<span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='<?php echo $this->getReviewsUrl(); ?>'; return false;"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()); ?></a></span>*/ ?>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getReviewsUrl(); ?>#review-form"><?php echo $this->__('Be the first to review this product'); ?></a></p>
<?php endif; ?>
