<?php
/**
* Acumen - Magento Theme
* http://gravitydept.com/to/acumen
*
* @author     Brendan Falkowski
* @package    gravdept_acumen
* @copyright  2010-2016 Gravity Department. All rights reserved.
* @version    2.0.0
*/
?>

<?php
// GravDept:
// Used in "My Reviews" & "Product View".
// Replaced URLs with custom string to anchor "#review-form".
//
// Original code:
/*<a href="<?php echo $this->getReviewsUrl(); ?>">*/
?>

<?php if ($this->getReviewsCount()): ?>
    <?php
    // GravDept:
    // Add microdata.
    ?>
    <div class="ratings" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <?php if ($this->getRatingSummary()): ?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary(); ?>%"></div>
            </div>

            <?php
            // GravDept:
            // Add microdata.
            // Divide by 20 to get rating out of 5 stars.
            ?>
            <meta itemprop="ratingValue" content="<?php echo $this->getRatingSummary() / 20; ?>">

            <?php
            // GravDept:
            // Add microdata.
            // Causes Google Rich Snippets to render "x votes" instead of "x reviews".
            ?>
            <?php /*<meta itemprop="ratingCount" content="<?php echo $this->getReviewsCount(); ?>">*/ ?>
        <?php endif; ?>

        <p class="rating-links">
            <?php
            // GravDept:
            // Custom URLs.
            ?>
            <a href="<?php echo $this->getData('product')->getProductUrl(); ?>#reviews">
                <?php
                // GravDept:
                // Add microdata.
                ?>
                <span itemprop="reviewCount"><?php echo $this->getReviewsCount(); ?></span>

                <?php if ($this->getReviewsCount() == 1): ?>
                    <?php echo $this->__('review'); ?>
                <?php else: ?>
                    <?php echo $this->__('reviews'); ?>
                <?php endif; ?>
            </a>

            <?php
            // GravDept:
            // Hide this.
            // Requires standalone review page.
            ?>
            <?php /*
            <a class="add-your-review" href="<?php echo $this->getReviewsUrl(); ?>#add-review">
                <?php echo $this->__('Add Your Review'); ?>
            </a>
            */ ?>

            <?php
            // GravDept:
            // Hide this.
            // Former solution that did not work when URL suffixes were added.
            ?>
            <?php /*<a href="<?php echo $this->getUrl('') . $this['product']['url_key'] ?>#add-review">*/ ?>
        </p>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <?php
    // GravDept:
    // Hide this.
    // Requires standalone review page.
    ?>
    <?php /*
    <p class="no-rating">
        <a href="<?php echo $this->getReviewsUrl(); ?>#add-review">
            <?php echo $this->__('Write A Review'); ?>
        </a>
    </p>
    */ ?>

    <p class="no-rating">
        <a class="button button--s button--subtle" href="<?php echo $this->getUrl('') . $this['product']['url_key']; ?>#add-review">
            <?php echo $this->__('Write A Review'); ?>
        </a>
    </p>
<?php endif; ?>
